pages:
  stage: deploy
  script:
    - mkdir public
    - cd src/ASCII-Video
    - find . -type f ! -name 'src/ASCII-Video/ji.mp4' -exec cp --parents {} ../../public/ \;
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH