pages:
  stage: deploy
  script:
    - mkdir public
    - cp -r src/ASCII-Video/* public/  # ← 只复制 src/l 目录下的文件
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH