pages:
  stage: deploy
  script:
    - mkdir public
    - rsync -av --exclude='ji.mp4' src/ASCII-Video/ public/   # 排除文件 & 目录
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH